version: "3"
services:
  videoroom_advanced:
    image: membraneframework/demo_webrtc_videoroom_advanced:latest
    network_mode: "host"
    environment:
      VIRTUAL_HOST: "videoroom.membraneframework.org"
      USE_INTEGRATED_TURN: "true"
      INTEGRATED_TURN_IP: "65.21.244.250"
      INTEGRATED_TURN_PORT_RANGE: "50000-65355"
      INTEGRATED_TCP_TURN_PORT: "49999"
      
